apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 10m
  url: https://github.com/emage-automation/customer-template.git
  ref:
    branch: template-demo
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./prod
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
